apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tsignal
  name: tsignal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tsignal
      name: tsignal
    spec:
      containers:
        - name: tsignal
          image: gcr.io/cpe-data/tsignal:0.2.5
          imagePullPolicy: Always
          env:
            - name: T_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: tsignal-tw-key
                  key: T_CONSUMER_KEY
            - name: T_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: tsignal-tw-secret
                  key: T_CONSUMER_SECRET
            - name: T_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tsignal-tw-token
                  key: T_ACCESS_TOKEN
            - name: T_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: tsignal-tw-access
                  key: T_ACCESS_SECRET
            - name: GCLOUD_PROJECT
              valueFrom:
                secretKeyRef:
                  name: tsignal-gcloud-project
                  key: GCLOUD_PROJECT
            - name: GCLOUD_INSTANCE
              valueFrom:
                secretKeyRef:
                  name: tsignal-spanner-instance
                  key: GCLOUD_INSTANCE
            - name: GCLOUD_DB
              valueFrom:
                secretKeyRef:
                  name: tsignal-spanner-db
                  key: GCLOUD_DB
          volumeMounts:
            - name: "service-account"
              mountPath: "/var/run/secret/cloud.google.com"
            - name: "certs"
              mountPath: "/etc/ssl/certs"
      volumes:
        - name: "service-account"
          secret:
            secretName: "tsignal-sa"
        - name: "certs"
          hostPath:
            path: "/etc/ssl/certs"
